Template repository changes: remal-github-actions/template-composite (#4)
Co-authored-by: remal-github-actions <77626445+remal-github-actions+sync-with-template@users.noreply.github.com>

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -77,6 +77,10 @@ jobs:
       id: get-version
       run: |
         VERSION=$(yq '.version' action.yml)
+        if [[ "$VERSION" == "null" ]]; then
+          echo "::error::Couldn't read version from action.yml"
+          exit 1
+        fi
         echo "version=$VERSION" | tee -a $GITHUB_OUTPUT
 
     - name: Create tag
